name: Build and Deploy to Firebase Hosting

on:
  push:
    branches: [ master ]

jobs:
  build-resume:
    name: Build resume
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts/resume
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: out-resume
          path: ../../out/resume
  build-home:
    name: Build home
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts/home
    steps:
      - run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: out-home
          path: ../../out/home
  deploy-firebase-hosting:
    needs:
      - build-resume
      - build-home
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
      - uses: actions/download-artifact@v2
        with:
          name: out-resume
          path: out/resume
      - uses: actions/download-artifact@v2
        with:
          name: out-home
          path: out/home
      - run: npm -g install firebase-tools
      - run: firebase deploy --only hosting

