name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  build-resume:
    name: Build resume
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts/resume
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: out-resume
          path: ../../out/resume
  build-home:
    name: Build home
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts/home
    steps:
      - run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: out-home
          path: ../../out/home
  build_and_preview:
    runs-on: ubuntu-20.04
    needs:
      - build-resume
      - build-home
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request' }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: out-resume
          path: out/resume
      - uses: actions/download-artifact@v2
        with:
          name: out-home
          path: out/home
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MICHAELLEE8_COM }}"
          projectId: michaellee8-com
  build_and_deploy:
    runs-on: ubuntu-20.04
    needs:
      - build-resume
      - build-home
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: out-resume
          path: out/resume
      - uses: actions/download-artifact@v2
        with:
          name: out-home
          path: out/home
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MICHAELLEE8_COM }}"
          channelId: live
          projectId: michaellee8-com
