name: Build and Preview to Firebase Hosting

on: pull_request

jobs:
  build-home:
    name: Build home
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: cd ./scripts/home && npm ci && npm run build && cd ../../
      - uses: actions/upload-artifact@v4
        with:
          name: out-home
          path: out/home
  preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    needs:
      - build-home
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: out-home
          path: out/home
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MICHAELLEE8_COM }}"
          projectId: michaellee8-com
